# Site specific settings
title: "My Notes"
name: "Pewpew notes"
baseurl: "/"
url: "https://pewpewnotes.github.io/"
description: "A simple site to make notes accessible from kindle"

# remote_theme: dirkfabisch/mediator
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-remote-theme
