# The Site Configuration

# Import the theme
remote_theme: cotes2020/jekyll-theme-chirpy
# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
baseurl: 'pewpewnotes'

# the HTML language tag › https://www.w3.org/International/questions/qa-choosing-language-tags
lang: en-US

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Shanghai

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# --------------------------
title: Chirpy                          # the main title

tagline: A text-focused Jekyll theme   # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  A minimal, portfolio, sidebar,
  bootstrap Jekyll theme with responsive web design
  and focuses on text presentation.
# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: ''

github:
  username: pewpewnotes           # change to your github username

twitter:
  username: twitter_username            # change to your twitter username

