# Site specific settings
title: "My Notes"
name: "Pewpew notes"
baseurl: ""
url: "http://pewpewnotes.github.io/"
description: "A simple site to make notes accessible from kindle"

remote_theme: chesterhow/tale
# Site general settings
lang: "en"

