# Site specific settings
title: "My Notes"
name: "Pewpew notes"
baseurl: ""
url: "https://pewpewnotes.github.io/"
description: "A simple site to make notes accessible from kindle"
logo_url: "https://avatars.githubusercontent.com/u/26499754?v=4"
author_name: "Kei Tachikawa"

# remote_theme: dirkfabisch/mediator
#remote_theme: bradleytaunt/ET-Jekyll
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-remote-theme
#remote_theme: heiswayi/the-plain
#remote_theme: cotes2020/jekyll-theme-chirpy
# remote_theme: mattr/darkmattr
# remote_theme: broccolini/athena
#remote_theme: mmistakes/so-simple-theme
# remote_theme: dracula/gh-pages
remote_theme: sharadcodes/jekyll-theme-dark-reader
